name: Update Exchange Tickers

on:
  push:
    branches: [main]
  schedule:
    # Run on the first day of each quarter (Jan 1, Apr 1, Jul 1, Oct 1) at 01:00 UTC
    - cron: "0 1 1 1,4,7,10 *"

jobs:
  update-tickers:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing to the repository

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper git operations

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ticker collection scripts
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python get_ticker_list_by_exchange.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add exchange_tickers.json tickers_with_type.json nyse_nasdaq_tickers.json nyse_nasdaq_tickers_etf.json nyse_nasdaq_tickers_cs.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ticker data on $(date)"
          git push origin HEAD:${GITHUB_REF}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
